version: '3.7'

services:
  db:
    container_name: manansala-db
    platform: linux/x86_64
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root